plugins {
    alias(libs.plugins.android.application)

    id 'com.google.gms.google-services'
}

android {

    namespace 'com.example.tripbuddy'
    compileSdk 34

    defaultConfig {

        applicationId "com.example.tripbuddy"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }


    buildFeatures {
        viewBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}


    dependencies {

        implementation libs.appcompat
        implementation 'com.google.android.material:material:1.11.0'
        implementation libs.constraintlayout

        implementation 'androidx.activity:activity:1.8.2'

        implementation 'androidx.lifecycle:lifecycle-viewmodel:2.6.2'
        implementation 'androidx.lifecycle:lifecycle-livedata:2.6.2'

        implementation 'androidx.navigation:navigation-fragment:2.7.5'
        implementation 'androidx.navigation:navigation-ui:2.7.5'

        implementation 'androidx.room:room-runtime:2.6.1'
        annotationProcessor 'androidx.room:room-compiler:2.6.1'

        implementation platform('com.google.firebase:firebase-bom:33.1.0')
        implementation 'com.google.firebase:firebase-auth'
        implementation 'com.google.firebase:firebase-database'

        testImplementation libs.junit
        androidTestImplementation libs.ext.junit
        androidTestImplementation libs.espresso.core
    }
